// This file is generated by `npm run contract:generate`.
// Source snapshot: package.json + scripts/contract-source.json
// Do not edit by hand.

export interface ContractMetadata {
  readonly binName: "gonkagate-codex";
  readonly binPath: "bin/gonkagate-codex.js";
  readonly cliVersion: "0.1.0";
  readonly packageName: "@gonkagate/codex-setup";
  readonly publicEntrypoint: "npx @gonkagate/codex-setup";
  readonly verifiedCodex: typeof import("./contract-definitions.js").VERIFIED_CODEX_CONTRACT;
}

export const CONTRACT_METADATA: ContractMetadata;
