// This file is generated by `npm run contract:generate`.
// Source snapshot: scripts/contract-source.json
// Do not edit by hand.

export const VERIFIED_CODEX_CONTRACT: {
  readonly minVersion: "0.118.0";
  readonly modelCatalogVersion: "rust-v0.118.0";
  readonly verifiedDate: "2026-04-02";
};

export type VerifiedCodexContractDefinition = typeof VERIFIED_CODEX_CONTRACT;
