// This file is generated by `npm run contract:generate`.
// Source snapshot: scripts/contract-source.json
// Do not edit by hand.

export const SUPPORTED_MODELS_CONTRACT: readonly [
  {
    readonly key: "gpt-5.4";
    readonly displayName: "GPT-5.4";
    readonly modelId: "gpt-5.4";
    readonly description: "Current validated GonkaGate model for Codex CLI.";
    readonly isDefault: true;
  },
];

export type SupportedModelContractDefinition =
  (typeof SUPPORTED_MODELS_CONTRACT)[number];

export const VERIFIED_CODEX_CONTRACT: {
  readonly minVersion: "0.118.0";
  readonly modelCatalogVersion: "rust-v0.118.0";
  readonly verifiedDate: "2026-04-02";
};

export type VerifiedCodexContractDefinition = typeof VERIFIED_CODEX_CONTRACT;
